/** @jsxImportSource react */
import React from 'react';
import type { Metadata } from "next";
import "@/app/styles/globals.css";
import Header from "@/app/Header";
import {Quicksand} from "next/font/google";
import localFont from "next/font/local";
import Footer from "@/app/Footer";
import Shared from "@/app/Shared";
import {deviceBreakpoints} from "@/app/styles/device-breakpoints";

// const rouge_script = Rouge_Script({ weight: "400" });
const quicksand = Quicksand();
const script_12_bt = localFont({
    src: "./fonts/Feelfree.ttf",
    weight: "100 900",
    declarations: [{ prop: "size-adjust", value: "180%" }]
});

export const metadata: Metadata = {
    title: "TechKun",
    description: "Generated by create next app",
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" style={{
            "--mobile-s": `${deviceBreakpoints.mobileS}px`,
            "--mobile-m": `${deviceBreakpoints.mobileM}px`,
            "--mobile-l": `${deviceBreakpoints.mobileL}px`,
            "--tablet": `${deviceBreakpoints.tablet}px`,
            "--laptop": `${deviceBreakpoints.laptop}px`,
            "--laptop-l": `${deviceBreakpoints.laptopL}px`,
            "--desktop": `${deviceBreakpoints.desktop}px`
        } as React.CSSProperties}>
            <body>
                <Header />
                {children}
                <Footer />
                <Shared />
            </body>
        </html>
    );
}
