/** @jsxImportSource react */
import React from 'react';
import type { Metadata } from "next";
import "@/app/styles/globals.css";
import Header from "@/app/Header";
import localFont from "next/font/local";
import Footer from "@/app/Footer";
import Shared from "@/app/Shared";
import generatedCss from "@/app/styles/generated-css";

const Quicksand = localFont({
    src: "./fonts/Quicksand-VariableFont_wght.ttf",
    weight: "100 900"
});

export const metadata: Metadata = {
    title: "TechKun",
    description: "Generated by create next app",
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <style dangerouslySetInnerHTML={{ __html: generatedCss }} />
            </head>
            <body>
                <Shared />
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
