/** @jsxImportSource react */
import React from 'react';
import type { Metadata } from "next";
import "@/app/theme/globals.css";
import Header from "@/app/Header";
import {Quicksand} from "next/font/google";
import localFont from "next/font/local";
import Footer from "@/app/Footer";
import Shared from "@/app/Shared";

const quicksand = Quicksand();
const script_12_bt = localFont({
    src: "./fonts/SCRPT12N.ttf",
    weight: "100 900"
});

export const metadata: Metadata = {
    title: "TechKun",
    description: "Generated by create next app",
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header />
                <main className='overflow-hidden'>{children}</main>
                <Footer />
                <Shared />
            </body>
        </html>
    );
}
